import { QuizFormat } from "../../type";

export const toeicStandard: QuizFormat = {
  label: "TOEIC スタンダード",
  body: [
    {
      question: "Anyway",
      choices: ["しかし", "とにかく", "そのため", "もしも"],
      answer: "とにかく",
      partOfSpeech: 4,
    },
    {
      question: "Ship",
      choices: ["出荷する", "逃げる", "列車", "自動車"],
      answer: "出荷する",
      partOfSpeech: 2,
    },
    {
      question: "Attend",
      choices: ["出荷する", "無視する", "参加する", "避ける"],
      answer: "参加する",
      partOfSpeech: 2,
    },
    {
      question: "Successful",
      choices: ["未知の", "失敗した", "平均的な", "成功した"],
      answer: "成功した",
      partOfSpeech: 3,
    },
    {
      question: "Employee",
      choices: ["従業員", "雇用者", "顧客", "競争者"],
      answer: "従業員",
      partOfSpeech: 1,
    },
    {
      question: "Expand",
      choices: ["拡大する", "縮小する", "保持する", "除外する"],
      answer: "拡大する",
      partOfSpeech: 2,
    },
    {
      question: "Copy",
      choices: ["気絶する", "創造する", "コピーする", "無視する"],
      answer: "コピーする",
      partOfSpeech: 2,
    },
    {
      question: "Close",
      choices: ["閉じる", "開く", "遠ざける", "接近する"],
      answer: "閉じる",
      partOfSpeech: 2,
    },
    {
      question: "Weekly",
      choices: ["毎日の", "週刊の", "月刊の", "年間の"],
      answer: "週刊の",
      partOfSpeech: 3,
    },
    {
      question: "Prefer",
      choices: ["嫌う", "好む", "無視する", "避ける"],
      answer: "好む",
      partOfSpeech: 2,
    },
    {
      question: "Sign",
      choices: ["破棄する", "拒否する", "読む", "署名する"],
      answer: "署名する",
      partOfSpeech: 2,
    },
    {
      question: "Break",
      choices: ["逃げる", "建てる", "壊す", "無視する"],
      answer: "壊す",
      partOfSpeech: 2,
    },
    {
      question: "Document",
      choices: ["文書", "物語", "画像", "音楽"],
      answer: "文書",
      partOfSpeech: 1,
    },
    {
      question: "Quarter",
      choices: ["四半期", "全期間", "半期", "月期"],
      answer: "四半期",
      partOfSpeech: 1,
    },
    {
      question: "Department",
      choices: ["全体", "部門", "個人", "グループ"],
      answer: "部門",
      partOfSpeech: 1,
    },
    {
      question: "Accept",
      choices: ["無視する", "拒否する", "受け入れる", "疑う"],
      answer: "受け入れる",
      partOfSpeech: 2,
    },
    {
      question: "Allow",
      choices: ["矯正する", "禁止する", "無視する", "許可する"],
      answer: "許可する",
      partOfSpeech: 2,
    },
    {
      question: "Connect",
      choices: ["切断する", "接続する", "無視する", "避ける"],
      answer: "接続する",
      partOfSpeech: 2,
    },
    {
      question: "Recently",
      choices: ["最近", "以前", "将来", "常に"],
      answer: "最近",
      partOfSpeech: 4,
    },
    {
      question: "Another",
      choices: ["別の", "同じ", "唯一の", "最後の"],
      answer: "別の",
      partOfSpeech: 3,
    },

    {
      question: "Likely",
      choices: ["不可能な", "難しい", "ありそうな", "必要な"],
      answer: "ありそうな",
      partOfSpeech: 3,
    },
    {
      question: "Rate",
      choices: ["忍者", "上昇", "割合", "減少"],
      answer: "割合",
      partOfSpeech: 1,
    },
    {
      question: "Local",
      choices: ["外国の", "地元の", "遠隔の", "普遍的な"],
      answer: "地元の",
      partOfSpeech: 3,
    },
    {
      question: "Retire",
      choices: ["退職する", "始める", "継続する", "避ける"],
      answer: "退職する",
      partOfSpeech: 2,
    },
    {
      question: "Workplace",
      choices: ["学校", "家", "職場", "公園"],
      answer: "職場",
      partOfSpeech: 1,
    },
    {
      question: "Performance",
      choices: ["パフォーマンス", "失敗", "停止", "計画"],
      answer: "パフォーマンス",
      partOfSpeech: 1,
    },
    {
      question: "Native",
      choices: ["新しい", "外国の", "母国の", "古い"],
      answer: "母国の",
      partOfSpeech: 3,
    },
    {
      question: "Modern",
      choices: ["伝統的な", "古代の", "現代の", "未来の"],
      answer: "現代の",
      partOfSpeech: 3,
    },
    {
      question: "Satisfied",
      choices: ["満足した", "不満な", "興奮した", "混乱した"],
      answer: "満足した",
      partOfSpeech: 3,
    },
    {
      question: "Author",
      choices: ["著者", "聴衆", "批評家", "芸術家"],
      answer: "著者",
      partOfSpeech: 1,
    },
    {
      question: "Experienced",
      choices: ["古い", "未熟な", "新しい", "経験豊富な"],
      answer: "経験豊富な",
      partOfSpeech: 3,
    },
    {
      question: "Branch",
      choices: ["葉", "根", "枝", "花"],
      answer: "枝",
      partOfSpeech: 1,
    },
    {
      question: "Develop",
      choices: ["無視する", "破壊する", "開発する", "減少する"],
      answer: "開発する",
      partOfSpeech: 2,
    },
    {
      question: "Nearly",
      choices: ["ほぼ", "完全に", "全く", "まったくない"],
      answer: "ほぼ",
      partOfSpeech: 4,
    },
    {
      question: "Create",
      choices: ["作成する", "破壊する", "無視する", "減少する"],
      answer: "作成する",
      partOfSpeech: 2,
    },
    {
      question: "Bill",
      choices: ["報告書", "手紙", "請求書", "証明書"],
      answer: "請求書",
      partOfSpeech: 1,
    },
    {
      question: "Mail",
      choices: ["電話", "メール", "パッケージ", "郵便"],
      answer: "郵便",
      partOfSpeech: 1,
    },
    {
      question: "Total",
      choices: ["合計", "部分", "平均", "最大"],
      answer: "合計",
      partOfSpeech: 1,
    },
    {
      question: "Introduce",
      choices: ["削除する", "紹介する", "無視する", "減少する"],
      answer: "紹介する",
      partOfSpeech: 2,
    },
    {
      question: "Charge",
      choices: ["請求する", "放棄する", "保存する", "減少する"],
      answer: "請求する",
      partOfSpeech: 2,
    },

    {
      question: "Profit",
      choices: ["投資", "損失", "利益", "コスト"],
      answer: "利益",
      partOfSpeech: 1,
    },
    {
      question: "Field",
      choices: ["荒野", "事務所", "教室", "野原"],
      answer: "野原",
      partOfSpeech: 1,
    },
    {
      question: "Affect",
      choices: ["阻害する", "無視する", "促進する", "影響する"],
      answer: "影響する",
      partOfSpeech: 2,
    },
    {
      question: "Figure",
      choices: ["数字", "形", "図", "例"],
      answer: "数字",
      partOfSpeech: 1,
    },
    {
      question: "Work",
      choices: ["働く", "休む", "遊ぶ", "学ぶ"],
      answer: "働く",
      partOfSpeech: 2,
    },
    {
      question: "Original",
      choices: ["新しい", "コピーの", "伝統的な", "オリジナルの"],
      answer: "オリジナルの",
      partOfSpeech: 3,
    },
    {
      question: "Neighborhood",
      choices: ["国外", "市内", "郊外", "近所"],
      answer: "近所",
      partOfSpeech: 1,
    },
    {
      question: "Environment",
      choices: ["環境", "社会", "経済", "政治"],
      answer: "環境",
      partOfSpeech: 1,
    },
    {
      question: "Consumer",
      choices: ["生産者", "消費者", "販売者", "仲介者"],
      answer: "消費者",
      partOfSpeech: 1,
    },
    {
      question: "Exhibition",
      choices: ["展示", "公演", "講義", "競争"],
      answer: "展示",
      partOfSpeech: 1,
    },
    {
      question: "Cafeteria",
      choices: ["レストラン", "カフェテリア", "図書館", "劇場"],
      answer: "カフェテリア",
      partOfSpeech: 1,
    },
    {
      question: "Consider",
      choices: ["無視する", "考える", "実行する", "拒否する"],
      answer: "考える",
      partOfSpeech: 2,
    },
    {
      question: "Improvement",
      choices: ["改善", "悪化", "停滞", "変化"],
      answer: "改善",
      partOfSpeech: 1,
    },
    {
      question: "Possibility",
      choices: ["可能性", "不可能", "確実性", "疑問"],
      answer: "可能性",
      partOfSpeech: 1,
    },
    {
      question: "Regard",
      choices: ["対抗して", "無視して", "みなす", "一致して"],
      answer: "みなす",
      partOfSpeech: 2,
    },
    {
      question: "Lack",
      choices: ["適度", "過剰", "不足", "等しい"],
      answer: "不足",
      partOfSpeech: 1,
    },
    {
      question: "Available",
      choices: ["利用可能な", "不可能な", "隠された", "限定された"],
      answer: "利用可能な",
      partOfSpeech: 3,
    },
    {
      question: "Prevent",
      choices: ["防ぐ", "促進する", "許可する", "無視する"],
      answer: "防ぐ",
      partOfSpeech: 2,
    },
    {
      question: "Praise",
      choices: ["罰する", "批判する", "無視する", "褒める"],
      answer: "褒める",
      partOfSpeech: 2,
    },
    {
      question: "Excellent",
      choices: ["優れた", "平均的な", "劣った", "新しい"],
      answer: "優れた",
      partOfSpeech: 3,
    },

    {
      question: "Announce",
      choices: ["質問する", "発表する", "応答する", "議論する"],
      answer: "発表する",
      partOfSpeech: 2,
    },
    {
      question: "Round-trip",
      choices: ["往復の", "片道の", "停止した", "延長した"],
      answer: "往復の",
      partOfSpeech: 3,
    },
    {
      question: "Opening",
      choices: ["開始", "終了", "継続", "遅延"],
      answer: "開始",
      partOfSpeech: 1,
    },
    {
      question: "Result",
      choices: ["過程", "原因", "結果", "計画"],
      answer: "結果",
      partOfSpeech: 1,
    },
    {
      question: "Report",
      choices: ["批評", "無視", "提案", "報告"],
      answer: "報告",
      partOfSpeech: 1,
    },
    {
      question: "Recover",
      choices: ["回復する", "悪化する", "停止する", "失う"],
      answer: "回復する",
      partOfSpeech: 2,
    },
    {
      question: "Study",
      choices: ["研究する", "遊ぶ", "無視する", "延期する"],
      answer: "研究する",
      partOfSpeech: 2,
    },
    {
      question: "Research",
      choices: ["推測", "調査", "無視", "実行"],
      answer: "調査",
      partOfSpeech: 1,
    },
    {
      question: "Demand",
      choices: ["需要", "提供", "拒否", "無視"],
      answer: "需要",
      partOfSpeech: 1,
    },
    {
      question: "Hire",
      choices: ["雇う", "解雇する", "昇進する", "転職する"],
      answer: "雇う",
      partOfSpeech: 2,
    },
    {
      question: "Tour",
      choices: ["休憩", "作業", "ツアー", "会議"],
      answer: "ツアー",
      partOfSpeech: 1,
    },
    {
      question: "Fare",
      choices: ["品質", "料金", "サービス", "運賃"],
      answer: "運賃",
      partOfSpeech: 1,
    },
    {
      question: "Necessary",
      choices: ["不要な", "余分な", "必要な", "稀な"],
      answer: "必要な",
      partOfSpeech: 3,
    },
    {
      question: "Approach",
      choices: ["退去", "接近", "無視", "反対"],
      answer: "接近",
      partOfSpeech: 2,
    },
    {
      question: "Aware",
      choices: ["意識して", "無知な", "無関心な", "混乱して"],
      answer: "意識して",
      partOfSpeech: 3,
    },
    {
      question: "Increasingly",
      choices: ["ますます", "減少して", "一定で", "たまに"],
      answer: "ますます",
      partOfSpeech: 4,
    },
    {
      question: "Former",
      choices: ["将来の", "現在の", "以前の", "永遠の"],
      answer: "以前の",
      partOfSpeech: 3,
    },
    {
      question: "Cause",
      choices: ["答え", "結果", "方法", "原因"],
      answer: "原因",
      partOfSpeech: 1,
    },
    {
      question: "Pleased",
      choices: ["混乱して", "不満な", "満足して", "興奮して"],
      answer: "満足して",
      partOfSpeech: 3,
    },
    {
      question: "Responsible",
      choices: ["責任がある", "無責任な", "関係ない", "無関心な"],
      answer: "責任がある",
      partOfSpeech: 3,
    },

    {
      question: "Appointment",
      choices: ["遅延", "解雇", "予約", "拒絶"],
      answer: "予約",
      partOfSpeech: 1,
    },
    {
      question: "Arrangement",
      choices: ["同意", "混乱", "拒絶", "手配"],
      answer: "手配",
      partOfSpeech: 1,
    },
    {
      question: "Full-time",
      choices: ["フルタイムの", "パートタイムの", "一時的な", "自由業の"],
      answer: "フルタイムの",
      partOfSpeech: 3,
    },
    {
      question: "Absolutely",
      choices: ["絶対に", "たまに", "時々", "まったくない"],
      answer: "絶対に",
      partOfSpeech: 4,
    },
    {
      question: "Resume",
      choices: ["停止する", "再開する", "始める", "終える"],
      answer: "再開する",
      partOfSpeech: 2,
    },
    {
      question: "Note",
      choices: ["注意する", "無視する", "忘れる", "破棄する"],
      answer: "注意する",
      partOfSpeech: 2,
    },
    {
      question: "Client",
      choices: ["パートナー", "提供者", "競合", "顧客"],
      answer: "顧客",
      partOfSpeech: 1,
    },
    {
      question: "Post",
      choices: ["保存する", "削除する", "投稿する", "無視する"],
      answer: "投稿する",
      partOfSpeech: 2,
    },
    {
      question: "Directly",
      choices: ["直接に", "間接的に", "遠回しに", "全くない"],
      answer: "直接に",
      partOfSpeech: 4,
    },
    {
      question: "Blame",
      choices: ["非難する", "褒める", "無視する", "支援する"],
      answer: "非難する",
      partOfSpeech: 2,
    },
    {
      question: "Expect",
      choices: ["拒否する", "無視する", "期待する", "疑う"],
      answer: "期待する",
      partOfSpeech: 2,
    },
    {
      question: "Broadcast",
      choices: ["隠す", "中止する", "記録する", "放送する"],
      answer: "放送する",
      partOfSpeech: 2,
    },
    {
      question: "Policy",
      choices: ["方針", "例外", "誤り", "提案"],
      answer: "方針",
      partOfSpeech: 1,
    },
    {
      question: "Offer",
      choices: ["無視する", "拒否する", "提供する", "要求する"],
      answer: "提供する",
      partOfSpeech: 2,
    },
    {
      question: "Forward",
      choices: ["前進する", "後退する", "停止する", "無視する"],
      answer: "前進する",
      partOfSpeech: 2,
    },
    {
      question: "Firmly",
      choices: ["弱く", "しっかりと", "まれに", "たまに"],
      answer: "しっかりと",
      partOfSpeech: 4,
    },
    {
      question: "Divide",
      choices: ["統一する", "結合する", "無視する", "分ける"],
      answer: "分ける",
      partOfSpeech: 2,
    },
    {
      question: "Content",
      choices: ["混乱", "不満", "興奮", "内容"],
      answer: "内容",
      partOfSpeech: 3,
    },
    {
      question: "Guided",
      choices: ["案内された", "放置された", "無視された", "隠された"],
      answer: "案内された",
      partOfSpeech: 3,
    },
    {
      question: "Degree",
      choices: ["程度", "否定", "同意", "確認"],
      answer: "程度",
      partOfSpeech: 1,
    },

    {
      question: "Located",
      choices: ["動いた", "失われた", "位置して", "静止した"],
      answer: "位置して",
      partOfSpeech: 3,
    },
    {
      question: "Welcome",
      choices: ["無視する", "拒否する", "歓迎する", "批判する"],
      answer: "歓迎する",
      partOfSpeech: 2,
    },
    {
      question: "Inform",
      choices: ["疑う", "隠す", "忘れる", "知らせる"],
      answer: "知らせる",
      partOfSpeech: 2,
    },
    {
      question: "Double",
      choices: ["二倍にする", "半分にする", "維持する", "無視する"],
      answer: "二倍にする",
      partOfSpeech: 2,
    },
    {
      question: "Crowded",
      choices: ["空いている", "混雑した", "静かな", "広い"],
      answer: "混雑した",
      partOfSpeech: 3,
    },
    {
      question: "Familiar",
      choices: ["見知らぬ", "なじみのある", "新しい", "古い"],
      answer: "なじみのある",
      partOfSpeech: 3,
    },
    {
      question: "Earn",
      choices: ["稼ぐ", "失う", "節約する", "投資する"],
      answer: "稼ぐ",
      partOfSpeech: 2,
    },
    {
      question: "Operate",
      choices: ["操作する", "停止する", "破壊する", "無視する"],
      answer: "操作する",
      partOfSpeech: 2,
    },
    {
      question: "Aisle",
      choices: ["入口", "部屋", "席", "通路"],
      answer: "通路",
      partOfSpeech: 1,
    },
    {
      question: "Mention",
      choices: ["否定する", "無視する", "言及する", "認める"],
      answer: "言及する",
      partOfSpeech: 2,
    },
    {
      question: "Attract",
      choices: ["驚かせる", "遠ざける", "無視する", "引き付ける"],
      answer: "引き付ける",
      partOfSpeech: 2,
    },
    {
      question: "Highly",
      choices: ["非常に", "ほとんどない", "時々", "まったく"],
      answer: "非常に",
      partOfSpeech: 4,
    },
    {
      question: "Serious",
      choices: ["楽しい", "軽薄な", "真剣な", "気楽な"],
      answer: "真剣な",
      partOfSpeech: 3,
    },
    {
      question: "Duty",
      choices: ["自由", "権利", "選択", "義務"],
      answer: "義務",
      partOfSpeech: 1,
    },
    {
      question: "District",
      choices: ["曖昧", "地区", "同じ", "携帯"],
      answer: "地区",
      partOfSpeech: 3,
    },
    {
      question: "Private",
      choices: ["個人的な", "公共の", "集団的な", "全体的な"],
      answer: "個人的な",
      partOfSpeech: 3,
    },
    {
      question: "Reasonable",
      choices: ["手ごろな", "非合理な", "過度な", "不足な"],
      answer: "手ごろな",
      partOfSpeech: 3,
    },
    {
      question: "Correct",
      choices: ["間違った", "正しい", "不確かな", "不明瞭な"],
      answer: "正しい",
      partOfSpeech: 3,
    },
    {
      question: "Function",
      choices: ["機能", "故障", "停止", "減少"],
      answer: "機能",
      partOfSpeech: 1,
    },
    {
      question: "Match",
      choices: ["違う", "反対する", "無視する", "一致する"],
      answer: "一致する",
      partOfSpeech: 2,
    },

    {
      question: "Fairly",
      choices: ["かなり", "不公平に", "部分的に", "完全に"],
      answer: "かなり",
      partOfSpeech: 4,
    },
    {
      question: "Fuel",
      choices: ["水", "燃料", "食料", "空気"],
      answer: "燃料",
      partOfSpeech: 1,
    },
    {
      question: "Book",
      choices: ["予約する", "キャンセルする", "読む", "書く"],
      answer: "予約する",
      partOfSpeech: 2,
    },
    {
      question: "Host",
      choices: ["訪問する", "参加する", "ホストする", "無視する"],
      answer: "ホストする",
      partOfSpeech: 2,
    },
    {
      question: "Additional",
      choices: ["追加の", "主要な", "不足の", "余分な"],
      answer: "追加の",
      partOfSpeech: 3,
    },
    {
      question: "Budget",
      choices: ["損失", "費用", "利益", "予算"],
      answer: "予算",
      partOfSpeech: 1,
    },
    {
      question: "Agency",
      choices: ["組織", "会社", "代理店", "政府"],
      answer: "代理店",
      partOfSpeech: 1,
    },
    {
      question: "Crew",
      choices: ["観客", "客", "乗組員", "競合者"],
      answer: "乗組員",
      partOfSpeech: 1,
    },
    {
      question: "Labor",
      choices: ["遊び", "休息", "労働", "学習"],
      answer: "労働",
      partOfSpeech: 1,
    },
    {
      question: "Overseas",
      choices: ["地方の", "国内の", "海外の", "近隣の"],
      answer: "海外の",
      partOfSpeech: 3,
    },
    {
      question: "Prove",
      choices: ["証明する", "否定する", "疑う", "忘れる"],
      answer: "証明する",
      partOfSpeech: 2,
    },
    {
      question: "Provide",
      choices: ["要求する", "取り除く", "無視する", "提供する"],
      answer: "提供する",
      partOfSpeech: 2,
    },
    {
      question: "Checkout",
      choices: ["逃げる", "チェックイン", "滞在", "チェックアウト"],
      answer: "チェックアウト",
      partOfSpeech: 1,
    },
    {
      question: "Standard",
      choices: ["標準", "異常", "例外", "ユニーク"],
      answer: "標準",
      partOfSpeech: 1,
    },
    {
      question: "Practical",
      choices: ["理論的な", "実用的な", "非現実的な", "抽象的な"],
      answer: "実用的な",
      partOfSpeech: 3,
    },
    {
      question: "Ability",
      choices: ["能力", "無力", "欠如", "過剰"],
      answer: "能力",
      partOfSpeech: 1,
    },
    {
      question: "Cooperation",
      choices: ["反対", "競争", "無視", "協力"],
      answer: "協力",
      partOfSpeech: 1,
    },
    {
      question: "Surprisingly",
      choices: ["驚くほど", "予想通り", "当然", "まったくない"],
      answer: "驚くほど",
      partOfSpeech: 4,
    },
    {
      question: "Handling",
      choices: ["破壊", "放棄", "無視", "取り扱い"],
      answer: "取り扱い",
      partOfSpeech: 1,
    },
    {
      question: "Encourage",
      choices: ["励ます", "阻止する", "無視する", "批判する"],
      answer: "励ます",
      partOfSpeech: 2,
    },

    {
      question: "Deliver",
      choices: ["拒否する", "受け取る", "配達する", "無視する"],
      answer: "配達する",
      partOfSpeech: 2,
    },
    {
      question: "Current",
      choices: ["未来の", "過去の", "現在の", "不定の"],
      answer: "現在の",
      partOfSpeech: 3,
    },
    {
      question: "Interview",
      choices: ["議会", "演説", "講義", "面接"],
      answer: "面接",
      partOfSpeech: 1,
    },
    {
      question: "Following",
      choices: ["次の", "前の", "同時の", "関係ない"],
      answer: "次の",
      partOfSpeech: 3,
    },
    {
      question: "Supply",
      choices: ["減少する", "供給する", "拒否する", "無視する"],
      answer: "供給する",
      partOfSpeech: 2,
    },
    {
      question: "Bulb",
      choices: ["電球", "ランプ", "スイッチ", "コード"],
      answer: "電球",
      partOfSpeech: 1,
    },
    {
      question: "Worth",
      choices: ["壁の", "無価値な", "価値がある", "安価な"],
      answer: "価値がある",
      partOfSpeech: 3,
    },
    {
      question: "Survey",
      choices: ["飲食", "推測", "無視", "調査"],
      answer: "調査",
      partOfSpeech: 1,
    },
    {
      question: "Nearby",
      choices: ["近くの", "遠い", "関連ない", "反対の"],
      answer: "近くの",
      partOfSpeech: 3,
    },
    {
      question: "Suburb",
      choices: ["都市部", "郊外", "田舎", "中心街"],
      answer: "郊外",
      partOfSpeech: 1,
    },
    {
      question: "Preserve",
      choices: ["破棄する", "保存する", "無視する", "変更する"],
      answer: "保存する",
      partOfSpeech: 2,
    },
    {
      question: "Separate",
      choices: ["分ける", "結合する", "無視する", "混合する"],
      answer: "分ける",
      partOfSpeech: 2,
    },
    {
      question: "Contract",
      choices: ["提案", "拒否", "契約", "解除"],
      answer: "契約",
      partOfSpeech: 1,
    },
    {
      question: "Authority",
      choices: ["無視", "従属", "反対", "権威"],
      answer: "権威",
      partOfSpeech: 1,
    },
    {
      question: "Wage",
      choices: ["利益", "損失", "賃金", "投資"],
      answer: "賃金",
      partOfSpeech: 1,
    },
    {
      question: "Advance",
      choices: ["変化する", "後退する", "停止する", "進歩する"],
      answer: "進歩する",
      partOfSpeech: 2,
    },
    {
      question: "Throughout",
      choices: ["全体を通して", "部分的に", "時々", "一度も"],
      answer: "全体を通して",
      partOfSpeech: 5,
    },
    {
      question: "Effective",
      choices: ["遅い", "無効な", "効果的な", "急な"],
      answer: "効果的な",
      partOfSpeech: 3,
    },
    {
      question: "Typical",
      choices: ["典型的な", "異常な", "珍しい", "一般的でない"],
      answer: "典型的な",
      partOfSpeech: 3,
    },
  ],
};
