import { QuizFormat } from "../../type";

export const toeicStandard: QuizFormat = {
  label: "TOEIC スタンダード",
  body: [
    {
      question: "Consequence",
      choices: ["結果", "原因", "計画", "疑問"],
      answer: "結果",
      partOfSpeech: 1,
    },
    {
      question: "Sealed",
      choices: ["開封された", "密封された", "破壊された", "作成された"],
      answer: "密封された",
      partOfSpeech: 3,
    },
    {
      question: "Involved",
      choices: ["関与した", "無関係の", "拒絶された", "支持された"],
      answer: "関与した",
      partOfSpeech: 3,
    },
    {
      question: "Urgent",
      choices: ["緊急の", "重要な", "無視できる", "遅延の"],
      answer: "緊急の",
      partOfSpeech: 3,
    },
    {
      question: "Via",
      choices: ["経由", "目的地", "出発点", "方法"],
      answer: "経由",
      partOfSpeech: 5,
    },
    {
      question: "Laboratory",
      choices: ["研究所", "図書館", "教室", "オフィス"],
      answer: "研究所",
      partOfSpeech: 1,
    },
    {
      question: "Engagement",
      choices: ["結婚", "離婚", "約束", "解雇"],
      answer: "約束",
      partOfSpeech: 1,
    },
    {
      question: "Proudly",
      choices: ["悲しく", "誇らしく", "恥ずかしく", "怒って"],
      answer: "誇らしく",
      partOfSpeech: 4,
    },
    {
      question: "Launch",
      choices: ["キャンセルする", "終了する", "続ける", "開始する"],
      answer: "開始する",
      partOfSpeech: 2,
    },
    {
      question: "Significant",
      choices: ["否定的な", "無視できる", "小さな", "重要な"],
      answer: "重要な",
      partOfSpeech: 3,
    },
    {
      question: "Substantial",
      choices: ["大幅な", "軽微な", "仮想の", "一時的な"],
      answer: "大幅な",
      partOfSpeech: 3,
    },
    {
      question: "Overall",
      choices: ["部分的な", "全般的な", "特定の", "独特の"],
      answer: "全般的な",
      partOfSpeech: 3,
    },
    {
      question: "Committed",
      choices: ["献身的な", "無関心な", "反対する", "支持する"],
      answer: "献身的な",
      partOfSpeech: 3,
    },
    {
      question: "Altogether",
      choices: ["時々", "部分的に", "完全に", "まれに"],
      answer: "完全に",
      partOfSpeech: 4,
    },
    {
      question: "Household",
      choices: ["団体", "企業", "学校", "世帯"],
      answer: "世帯",
      partOfSpeech: 1,
    },
    {
      question: "Alter",
      choices: ["開始する", "維持する", "変更する", "終了する"],
      answer: "変更する",
      partOfSpeech: 2,
    },
    {
      question: "Assure",
      choices: ["保証する", "疑う", "拒絶する", "無視する"],
      answer: "保証する",
      partOfSpeech: 2,
    },
    {
      question: "Expose",
      choices: ["隠す", "晒す", "保護する", "無視する"],
      answer: "晒す",
      partOfSpeech: 2,
    },
    {
      question: "Remark",
      choices: ["支持する", "無視する", "批判する", "言及する"],
      answer: "言及する",
      partOfSpeech: 2,
    },
    {
      question: "Pursue",
      choices: ["怒る", "避ける", "停止する", "追及する"],
      answer: "追求する",
      partOfSpeech: 2,
    },

    {
      question: "Decade",
      choices: ["年", "世紀", "月", "十年"],
      answer: "十年",
      partOfSpeech: 1,
    },
    {
      question: "Hesitate",
      choices: ["躊躇する", "進む", "急ぐ", "停止する"],
      answer: "躊躇する",
      partOfSpeech: 2,
    },
    {
      question: "Profitable",
      choices: ["有益な", "損失の", "無関心な", "困難な"],
      answer: "有益な",
      partOfSpeech: 3,
    },
    {
      question: "Adjustment",
      choices: ["修正", "維持", "調整", "無視"],
      answer: "調整",
      partOfSpeech: 1,
    },
    {
      question: "Component",
      choices: ["部品", "全体", "製品", "サービス"],
      answer: "部品",
      partOfSpeech: 1,
    },
    {
      question: "Adopt",
      choices: ["維持する", "放棄する", "変更する", "採用する"],
      answer: "採用する",
      partOfSpeech: 2,
    },
    {
      question: "Alternative",
      choices: ["代わりの", "同じ", "似ている", "異なる"],
      answer: "代わりの",
      partOfSpeech: 3,
    },
    {
      question: "Mutual",
      choices: ["相互の", "単独の", "独立した", "競合する"],
      answer: "相互の",
      partOfSpeech: 3,
    },
    {
      question: "Procedure",
      choices: ["結果", "手順", "問題", "解決"],
      answer: "手順",
      partOfSpeech: 1,
    },
    {
      question: "Interval",
      choices: ["終了", "開始", "間隔", "連続"],
      answer: "間隔",
      partOfSpeech: 1,
    },
    {
      question: "Craftspeople",
      choices: ["職人", "学生", "教師", "管理者"],
      answer: "職人",
      partOfSpeech: 1,
    },
    {
      question: "Venue",
      choices: ["家", "会議", "オフィス", "場所"],
      answer: "場所",
      partOfSpeech: 1,
    },
    {
      question: "Representative",
      choices: ["フォロワー", "代表者", "リーダー", "批評家"],
      answer: "代表者",
      partOfSpeech: 1,
    },
    {
      question: "Transportation",
      choices: ["教育", "休息", "運動", "交通"],
      answer: "交通",
      partOfSpeech: 1,
    },
    {
      question: "Invest",
      choices: ["引き出す", "投資する", "節約する", "消費する"],
      answer: "引き出す",
      partOfSpeech: 2,
    },
    {
      question: "Affordably",
      choices: ["手頃な価格で", "高価で", "無料で", "交渉で"],
      answer: "手頃な価格で",
      partOfSpeech: 4,
    },
    {
      question: "Findings",
      choices: ["結論", "探求", "発見", "仮説"],
      answer: "発見",
      partOfSpeech: 1,
    },
    {
      question: "Timely",
      choices: ["時宜にかなった", "遅れた", "早すぎる", "不適切な"],
      answer: "時宜にかなった",
      partOfSpeech: 3,
    },
    {
      question: "Promising",
      choices: ["平凡な", "疑わしい", "失敗した", "有望な"],
      answer: "有望な",
      partOfSpeech: 3,
    },
    {
      question: "Tip",
      choices: ["ヒント", "終わり", "開始", "中心"],
      answer: "ヒント",
      partOfSpeech: 1,
    },
    {
      question: "Stable",
      choices: ["不安定な", "安定した", "変動する", "減少する"],
      answer: "安定した",
      partOfSpeech: 3,
    },
    {
      question: "Steep",
      choices: ["急な", "緩やかな", "平坦な", "低い"],
      answer: "急な",
      partOfSpeech: 3,
    },
    {
      question: "Confident",
      choices: ["不安な", "確信している", "迷っている", "悲観的な"],
      answer: "確信している",
      partOfSpeech: 3,
    },
    {
      question: "Convinced",
      choices: ["確信している", "疑っている", "無関心な", "拒否している"],
      answer: "確信している",
      partOfSpeech: 3,
    },
    {
      question: "Retain",
      choices: ["放棄する", "保持する", "失う", "破壊する"],
      answer: "保持する",
      partOfSpeech: 2,
    },
    {
      question: "Enclose",
      choices: ["開ける", "無視する", "取り除く", "添付する"],
      answer: "添付する",
      partOfSpeech: 2,
    },
    {
      question: "Acquire",
      choices: ["失う", "獲得する", "拒否する", "放棄する"],
      answer: "獲得する",
      partOfSpeech: 2,
    },
    {
      question: "Related",
      choices: ["関連した", "無関係の", "対立する", "独立した"],
      answer: "関連した",
      partOfSpeech: 3,
    },
    {
      question: "Definitely",
      choices: ["多分", "おそらく", "間違いなく", "絶対にない"],
      answer: "間違いなく",
      partOfSpeech: 4,
    },
    {
      question: "Excerpt",
      choices: ["全文", "引用", "要約", "解釈"],
      answer: "引用",
      partOfSpeech: 1,
    },
    {
      question: "Distinguish",
      choices: ["混同する", "投げる", "統合する", "区別する"],
      answer: "区別する",
      partOfSpeech: 2,
    },
    {
      question: "Thorough",
      choices: ["表面的な", "徹底的な", "不完全な", "急いでいる"],
      answer: "徹底的な",
      partOfSpeech: 3,
    },
    {
      question: "Measurement",
      choices: ["計測", "推測", "推定", "無視"],
      answer: "計測",
      partOfSpeech: 1,
    },
    {
      question: "Circumstance",
      choices: ["結果", "意図", "計画", "事情"],
      answer: "事情",
      partOfSpeech: 1,
    },
    {
      question: "Overcome",
      choices: ["譲る", "失敗する", "克服する", "回避する"],
      answer: "克服する",
      partOfSpeech: 2,
    },
    {
      question: "Immense",
      choices: ["膨大な", "小さい", "平均的な", "限定された"],
      answer: "膨大な",
      partOfSpeech: 3,
    },
    {
      question: "Claim",
      choices: ["主張する", "拒否する", "無視する", "確認する"],
      answer: "主張する",
      partOfSpeech: 2,
    },
    {
      question: "Panel",
      choices: ["委員会", "グループ", "パネル", "個人"],
      answer: "パネル",
      partOfSpeech: 1,
    },
    {
      question: "Portion",
      choices: ["全体", "部分", "余剰", "不足"],
      answer: "部分",
      partOfSpeech: 1,
    },
    {
      question: "Personnel",
      choices: ["人事", "機器", "プログラム", "政策"],
      answer: "人事",
      partOfSpeech: 1,
    },
    {
      question: "Restore",
      choices: ["回復する", "破壊する", "無視する", "減少する"],
      answer: "回復する",
      partOfSpeech: 2,
    },
    {
      question: "Conduct",
      choices: ["認める", "実施する", "計画する", "キャンセルする"],
      answer: "実施する",
      partOfSpeech: 2,
    },
    {
      question: "Assume",
      choices: ["疑う", "拒否する", "仮定する", "確認する"],
      answer: "仮定する",
      partOfSpeech: 2,
    },
    {
      question: "Dependable",
      choices: ["信頼できる", "不安定な", "変更可能な", "危険な"],
      answer: "信頼できる",
      partOfSpeech: 3,
    },
    {
      question: "Accurate",
      choices: ["不正確な", "正確な", "曖昧な", "一般的な"],
      answer: "正確な",
      partOfSpeech: 3,
    },
    {
      question: "Appreciate",
      choices: ["無視する", "価値を認める", "減少させる", "拒否する"],
      answer: "価値を認める",
      partOfSpeech: 2,
    },
    {
      question: "Primary",
      choices: ["二次的な", "不要な", "高度な", "初等的な"],
      answer: "初等的な",
      partOfSpeech: 3,
    },
    {
      question: "Desirable",
      choices: ["望ましい", "不必要な", "避けるべき", "一時的な"],
      answer: "望ましい",
      partOfSpeech: 3,
    },
    {
      question: "Deposit",
      choices: ["撤回する", "保管する", "預金する", "借りる"],
      answer: "預金する",
      partOfSpeech: 2,
    },
    {
      question: "Completion",
      choices: ["開始", "中断", "完了", "継続"],
      answer: "完了",
      partOfSpeech: 1,
    },
    {
      question: "Appropriate",
      choices: ["適切な", "不適切な", "過剰な", "不足している"],
      answer: "適切な",
      partOfSpeech: 3,
    },
    {
      question: "Challenging",
      choices: ["簡単な", "難しい", "退屈な", "興味深い"],
      answer: "難しい",
      partOfSpeech: 3,
    },
    {
      question: "Factor",
      choices: ["結果", "要因", "解決策", "問題"],
      answer: "要因",
      partOfSpeech: 1,
    },
    {
      question: "Resident",
      choices: ["訪問者", "居住者", "外国人", "通行人"],
      answer: "居住者",
      partOfSpeech: 1,
    },
    {
      question: "Proof",
      choices: ["推測", "疑問", "仮説", "照明"],
      answer: "証明",
      partOfSpeech: 1,
    },
    {
      question: "Vote",
      choices: ["選挙", "投票する", "棄権する", "観察する"],
      answer: "投票する",
      partOfSpeech: 2,
    },
    {
      question: "Agreement",
      choices: ["合意", "対立", "無視", "競争"],
      answer: "合意",
      partOfSpeech: 1,
    },
    {
      question: "Extremely",
      choices: ["非常に", "わずかに", "まれに", "全く"],
      answer: "非常に",
      partOfSpeech: 4,
    },
    {
      question: "Physician",
      choices: ["患者", "看護師", "医師", "薬剤師"],
      answer: "医師",
      partOfSpeech: 1,
    },
    {
      question: "Track",
      choices: ["追跡する", "逃げる", "停止する", "無視する"],
      answer: "追跡する",
      partOfSpeech: 2,
    },
    {
      question: "Status",
      choices: ["位置", "状態", "速度", "方向"],
      answer: "状態",
      partOfSpeech: 1,
    },
    {
      question: "Crop",
      choices: ["植物", "収穫", "病害", "肥料"],
      answer: "収穫",
      partOfSpeech: 1,
    },
    {
      question: "Landscaping",
      choices: ["設計", "建設", "造園", "解体"],
      answer: "造園",
      partOfSpeech: 1,
    },
    {
      question: "Severe",
      choices: ["穏やかな", "厳しい", "軽い", "楽しい"],
      answer: "厳しい",
      partOfSpeech: 3,
    },
    {
      question: "Luxury",
      choices: ["必需品", "貧困", "節約", "贅沢"],
      answer: "贅沢",
      partOfSpeech: 1,
    },
    {
      question: "Output",
      choices: ["出力", "入力", "処理", "保存"],
      answer: "出力",
      partOfSpeech: 1,
    },
    {
      question: "Remote",
      choices: ["近い", "遠隔の", "直接的な", "連続した"],
      answer: "遠隔の",
      partOfSpeech: 3,
    },
    {
      question: "Resolve",
      choices: ["無視する", "拡大する", "混乱させる", "陥る"],
      answer: "解決する",
      partOfSpeech: 2,
    },
    {
      question: "Orientation",
      choices: ["方向性", "混乱", "一貫性", "不一致"],
      answer: "方向性",
      partOfSpeech: 1,
    },
    {
      question: "Packet",
      choices: ["ボックス", "容器", "パケット", "バッグ"],
      answer: "パケット",
      partOfSpeech: 1,
    },
    {
      question: "Spacious",
      choices: ["狭い", "広々とした", "混雑した", "限定された"],
      answer: "広々とした",
      partOfSpeech: 3,
    },
    {
      question: "Modest",
      choices: ["派手な", "謙虚な", "高慢な", "怠慢な"],
      answer: "謙虚な",
      partOfSpeech: 3,
    },
    {
      question: "Impose",
      choices: ["撤回する", "許可する", "避ける", "課す"],
      answer: "課す",
      partOfSpeech: 2,
    },
    {
      question: "Minimum",
      choices: ["最大", "最小", "平均", "合計"],
      answer: "最小",
      partOfSpeech: 1,
    },
    {
      question: "Debate",
      choices: ["協議", "討論", "合意", "無視"],
      answer: "討論",
      partOfSpeech: 1,
    },
    {
      question: "Checkup",
      choices: ["検査", "治療", "手術", "診断"],
      answer: "検査",
      partOfSpeech: 1,
    },
    {
      question: "Reverse",
      choices: ["進む", "戻る", "逆転", "維持"],
      answer: "逆転",
      partOfSpeech: 2,
    },
    {
      question: "Organize",
      choices: ["混乱させる", "捨てる", "破壊する", "取りまとめる"],
      answer: "取りまとめる",
      partOfSpeech: 2,
    },
    {
      question: "Replacement",
      choices: ["追加", "交換", "削除", "保持"],
      answer: "交換",
      partOfSpeech: 1,
    },
  ],
};
